// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvhughpxfvwujeebzxgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2aHVnaHB4ZnZ3dWplZWJ6eGdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NDA2MTEsImV4cCI6MjA2NjIxNjYxMX0.OzVx-7q3xqXKyl4_akzW6tcN_61yaZ38UlQtw2vQNQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);